config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'events#index'

  resources :events
  resources :users,  only: [:show]
  resources :events do
    resources :attendances
    resources :charges
    resources :events_pictures, only: [:new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :event
  belongs_to :participant, foreign_key: 'participant_id', class_name: "User"

  after_create :new_attendance

  def new_attendance
    AttendanceMailer.new_attendance(self).deliver_now
  end
end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :admin, foreign_key: 'admin_id', class_name: "User"
  has_many :participants, through: :attendances, class_name: 'User'
  has_many :attendances
  has_one_attached :event_picture

  validate :cant_start_in_the_past
  validate :duration_be_positive_and_multiple_of_5
  validates :title, presence: true, length: { in: 5..140 }
  validates :description, presence: true, length: { in: 20..1000}
  validates :price, presence: true
  validates_inclusion_of :price, :in => 1..1000
  validates :location, presence: true


  def duration_be_positive_and_multiple_of_5
    unless duration.present? && duration > 0 && duration % 5 == 0
      errors.add(:duration, "has to be positive and multiple of 5.")
    end
  end

  def cant_start_in_the_past
    unless start_date.present? && start_date > DateTime.now
      errors.add(:start_date, "must exist and can't be in the past")
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  has_many :events, foreign_key: 'admin_id', class_name: "Event"
  has_many :attendances
  
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description, presence: true, length: { minimum: 10 }

  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,  keys: [:first_name , :last_name, :description])
  end
  
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user!
  attr_accessor :user, :event

  def index
    @event = Event.find(params[:event_id])
    @attendances = @event.attendances
  end

  def new
    create
  end

  def create
    @attendance = Attendance.new(participant_id: current_user.id, stripe_customer_id: params[:token], event: Event.find(params[:event]))

    if @attendance.save 
      flash[:success] = "Vous participerez bien à cet event suite à votre paiement de #{Event.find(params[:event]).price} €"
      redirect_to :controller => 'events', :action => 'show', id: Event.find(params[:event]).id
    else
      flash[:danger] = "Nous n'avons pas réussi à créer votre particpation pour l'event"
      redirect_to controller: "events", :action => 'index'
    end
  end

  private

    def set_attendance
      @attendance = Attendance.find(params[:id])
    end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  @event = Event.find(params[:event_id])
  @amount = @event.price
  end
  
  def create
    @event = Event.find(params[:event_id])
    @token = params[:stripeToken]
  
    redirect_to new_event_attendance_path(event: @event,token: @token)
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show, :update, :destroy]
  attr_reader :events

  def index
    @events = Event.all 
  end

  def new
    @event = Event.new
  end

  def show 
    @event = Event.find(params[:id])
    @participants = Attendance.where(:event_id => @event.id)
    @admin =  @admin = User.find(@event.admin_id)
  end

  def create
    @event = Event.new(event_params)
    @event.admin_id = current_user.id

    if @event.save 
      flash[:success] = "Vous avez bien créé un event"
      redirect_to :controller => 'events', :action => 'show', id: @event.id
    else
      flash[:danger] = "Nous n'avons pas réussi à créer l'event pour la (ou les) raison(s) suivante(s) : #{@event.errors.full_messages.each {| message | message}.join(' , ')}"
      render :action => 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      flash[:success] = "Merci #{@event.admin.first_name} ! Nous avons pu modifier l'event : #{@event.title} "
      redirect_to :controller => 'events', :action => 'show', id: @event.id
    else
      flash[:danger] = "Nous n'avons pas réussi à modifier l'event"
      render :action => 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    if @event.destroy
      flash[:success] = "Merci #{@event.admin.first_name} ! Nous avons pu supprimer l'event : #{@event.title} "
      redirect_to :controller => 'events', :action => 'index' 
    else
      flash[:danger] = "Nous n'avons pas réussi à suppimer l'event ! "
      render :action => 'edit'
    end
  end


  private

  def event_params
    params.require(:event).permit(:title, :location, :start_date, :duration, :price, :description)
  end
end

app/controllers/events_pictures_controller.rb
class EventsPicturesController < ApplicationController
  before_action :authenticate_user!

  def new
    @event = Event.find(params[:event_id])
  end

  def create
    @event = Event.find(params[:event_id])
    @event.event_picture.attach(params[:event_picture])
    flash[:success] = "L'image liée à votre event a bien été ajoutée"
    redirect_to :controller => 'events', :action => 'show', id: @event.id
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :is_owner?, only: [:show]
  
  def show
    @user = current_user
    @events = Event.where(admin_id: current_user.id)
  end

  private 

  def is_owner?
    if current_user.id.to_i != params[:id].to_i
      flash[:danger] = "Vous ne pouvez pas acceder à cette page"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper

  def already_present?(event)
    Attendance.where(participant_id: current_user.id, event_id: event.id).size > 0
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def end_date(event)
    @event = Event.find(params[:id])
    @event.start_date + @event.duration*60
  end

  def is_owner?(id)
    if current_user.id == id
      return true
    else
      return false
    end
  end
end

app/helpers/events_pictures_helper.rb
module EventsPicturesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/index.html.erb
<h1 class="text-center" style="margin: 10px"> Ils participeront avec toi à ton event:  </h1>

<% @attendances.each do |attendance| %>
<div class="container text-center">
  <div class="row">
    <div class="col-lg" style="max-width: auto;"> 
      <div class="card border-warning m-4" style="height: 10rem">
        <div class="card-header"><%= attendance.participant.first_name %> <%= attendance.participant.last_name %></div>
          <div class="card-body">
            <h6 class="card-title">Voici l'email de contact de <%= attendance.participant.first_name %> : <%= attendance.participant.email %></h6>
            <p class="card-text">Tu peux lire ici la description de ton invité : <%= attendance.participant.description %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

<div class="text-center">
  <%= link_to "Modifier mon event", edit_event_path(@event), class: 'btn btn-outline-danger btn-sm'%>
</div>

app/views/charges/create.html.erb
<h2>Merci vous venez de payer <strong><%= @event.price %>€</strong>

app/views/charges/new.html.erb
<%= form_tag event_charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Prix: <%= @amount %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="GG brow"
          data-amount="<%= @amount * 100 %>"
          data-locale="auto"></script>
<% end %>

app/views/events/edit.html.erb
<div class=" col-md-12  row">
  <p class="col-lg-1" style="margin: 15px 0; "><%= link_to "Supprimer cet event", event_path(@event), method: :delete, data: {confirm: "Voulez-vous vraiment supprimer cet event ?"} , class: "btn btn-outline-danger btn-sm" %></p>
  <h1 class="col-lg-11 text-center" style="margin: 15px 0"> Editez votre event </h1>
</div>
<div class ='align-middle text-center'>
	<div class="card m-5 p-5" style="height:auto">
		<div class="card-body">
      <div class="row">
        <div class="col-md-8 offset-md-2">

          <%= form_with model: @event, local: true do |form| %>

          <div class="form-group row">
            <div class="col-lg-3"> <%= form.label :title, 'Titre' %> </div>
            <div class="col-lg-9">
              <%= form.text_field :title, class: "form-control"  %>
            </div>
          </div>

          <div class="form-group row">
            <div class="col-lg-3"> <%= form.label :location, 'Localisation' %> </div>
            <div class="col-lg-9">
              <%= form.text_field :location, class: "form-control"  %>
            </div>
          </div>

          <div class="form-group row">
            <div class="col-lg-3"> <%= form.label :start_date, 'Date' %> </div>
            <div class="col-lg-9">
              <%= form.datetime_select   :start_date, class: "form-control"  %>
            </div>
          </div>

          <div class="form-group row">
            <div class="col-lg-3"> <%= form.label :duration, 'Durée' %> </div>
            <div class="col-lg-9">
              <%= form.number_field :duration, {value: '15', min: 5, step: 5  } %>  (multiple de 5)
            </div>
          </div>

          <div class="form-group row">
            <div class="col-lg-3"> <%= form.label :price, 'Prix' %> </div>
            <div class="col-lg-9">
              <%= form.number_field :price, {value: '199', min: 1, max: 1000  } %>  (en euros)
            </div>
          </div>

          <div class="form-group row">
            <div class="col-lg-3"> <%= form.label :description, 'Description' %> </div>
            <div class="col-lg-9">
              <%= form.text_area :description, class: "form-control"  %>
            </div>
          </div>

          <div class="actions mt-5 row">
            <div class="col-lg-3"></div>
            <%= form.submit "Valider", class: "btn btn-outline-success btn-block col-lg-9", style: "margin: 10px 0;" %>
          </div>

            <% end %>
          </form>

          <div class="actions mt-5 row">
            <div class="col-lg-3"></div>
            <%= link_to "Ajouter une image", new_event_events_picture_path(@event), :class => "btn btn btn-block btn-outline-warning col-lg-9" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="jumbotron jumbotron-fluid text-center">
  <h1 class="display-4 pt-5 font-weight-bold text-center">Bienvenue sur Event-THP</h1>
  <%= link_to "Partagez votre event", new_event_path , class: "btn btn-success m-3" %>
</div>

<div class="col-12 text-center">
  <% @events.each do |event| %>
    <div class="card">
      <div class="card-body">
        <h5 class="mt-0 text-center"><%= event.title  %></h5>
        <p class="text-info"><%= event.start_date.strftime("%d %B %Y")%></p>
        <p>Le prix de cet événement sera de <%= event.price %> euros</p>
        <%= link_to "Afficher cet event", event_path(:id => event.id), class: 'btn btn-outline-success btn-sm' %>
      </div>
    </div>
  <% end %>
</div>

app/views/events/new.html.erb
<div class=" col-md-12  row">
  <p class="col-lg-1"></p>
  <h1 class="col-lg-11 text-center" style="margin: 15px 0"> Créez votre event </h1>
</div>
<div class ='align-middle text-center'>
	<div class="card m-5 p-5" style="height:auto">
		<div class="card-body">
      <div class="row">
        <div class="col-md-8 offset-md-2">

          <%= form_with model: @event, local: true do |form| %>

          <div class="form-group row">
            <div class="col-lg-3"> <%= form.label :title, 'Titre' %> </div>
            <div class="col-lg-9">
              <%= form.text_field :title, class: "form-control"  %>
            </div>
          </div>

          <div class="form-group row">
            <div class="col-lg-3"> <%= form.label :location, 'Localisation' %> </div>
            <div class="col-lg-9">
              <%= form.text_field :location, class: "form-control"  %>
            </div>
          </div>

          <div class="form-group row">
            <div class="col-lg-3"> <%= form.label :start_date, 'Date' %> </div>
            <div class="col-lg-9">
              <%= form.datetime_select   :start_date, class: "form-control"  %>
            </div>
          </div>

          <div class="form-group row">
            <div class="col-lg-3"> <%= form.label :duration, 'Durée' %> </div>
            <div class="col-lg-9">
              <%= form.number_field :duration, {value: '15', min: 5, step: 5  } %>  (multiple de 5)
            </div>
          </div>

          <div class="form-group row">
            <div class="col-lg-3"> <%= form.label :price, 'Prix' %> </div>
            <div class="col-lg-9">
              <%= form.number_field :price, {value: '199', min: 1, max: 1000  } %>  (en euros)
            </div>
          </div>

          <div class="form-group row">
            <div class="col-lg-3"> <%= form.label :description, 'Description' %> </div>
            <div class="col-lg-9">
              <%= form.text_area :description, class: "form-control"  %>
            </div>
          </div>

            <div class="actions mt-5 row">
              <div class="col-lg-3"></div>
              <%= form.submit "Valider", class: "btn btn-outline-success btn-block col-lg-9", style: "margin: 10px 0;" %>
            </div>

            <% end %>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="cardShowEvent" > 
  <div class="card border-secondary mb-3 text-center">
    <div class="card-header border-secondary Show"><%= @event.title %></div>
      <div class="card-body Show">
        <% if @event.event_picture.attached? %>
          <%= image_tag @event.event_picture, alt: 'event picture', class: "event_picture" %>
        <% end %>
        <h4 class="card-title"><%= @event.title%></h4>
        <p class="card-text">Le prix de cet événement sera de <%= @event.price %> euro et il se déroulera à <strong><%= @event.location %></strong></p>
        <p class="card-text">Le total de personnes participant à cet event est de <%= @participants.count %> personnes </p>
        <p class="card-text">Voici l'email de l'administrateur de l'event : <%= @admin.email %></p>
        <p>Cet event débutera le <span class="text-info"><%= @event.start_date.strftime("%d %B %Y, %H:%M")  %></span> et se finira le <span class="text-info"><%= end_date(@event).strftime("%d %B %Y, %H:%M") %></span></p>
      </div>
    </div>
  </div>
</div>

<div class="text-center" style="margin: 10px 0">
  <%= link_to "Revenir à l'accueil", root_path, class: 'btn btn-outline-warning btn-sm', style: 'margin-right: 10px' %>
  <% unless is_owner?(@event.admin_id) || already_present?(@event) %>
    <%= link_to "Participer à cet event", new_event_charge_path(event_id: @event.id), class: 'btn btn-outline-danger btn-sm' %>
  <% end %>
  <% if is_owner?(@event.admin_id) %>
    <%= link_to "Mon espace event", event_attendances_path(@event), class: 'btn btn-outline-danger btn-sm', style: 'margin-right: 10px' %>
  <% end %>
</div>

app/views/events_pictures/new.html.erb
<div class=" col-md-12  row">
  <p class="col-lg-1"></p>
  <h1 class="col-lg-11 text-center" style="margin: 15px 0"> Créez votre event </h1>
</div>
<div class ='align-middle text-center'>
	<div class="card m-5 p-5" style="height:auto">
		<div class="card-body">
      <div class="row">
        <div class="col-md-8 offset-md-2">

          <%= form_tag event_events_pictures_path(@event), multipart: true do %>
            <%= file_field_tag :event_picture %>
            <%= submit_tag "Envoyer l'image" , :class => "btn btn btn-block btn-outline-success mt-4"%>
          <% end %>

          </form>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert-dismissible fade show alert alert-<%= key %>"><%= value %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footercontain">
  <footer class="page-footer">
    <div class="footer-copyright text-center">© 2020 Copyright :
      <a href="https://event-thp.herokuapp.com/"> Event-thp.herokuapp.com </a>
    </div>
  </footer>
</div>

app/views/layouts/_navbar.html.erb
<header>

<!--Navbar-->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark scrolling-navbar">
    <%= link_to "Event-THP", root_path, :class => "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!--Links-->
      <ul class="navbar-nav mr-auto smooth-scroll">
        <li class="nav-item">
          <%= link_to "Accueil", root_path, :class => "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Créer un event", new_event_path , :class => "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item dropdown ">
            <a class="nav-link dropdown-toggle " id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Mon profil
            </a>
            <div class="dropdown-menu " aria-labelledby="navbarDropdown-connexion">
              <%= link_to current_user.first_name, user_path(:id => current_user.id), class: "dropdown-item" %>
              <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>
        <% if !user_signed_in? %>
          <li class="nav-item dropdown ">
            <a class="nav-link dropdown-toggle " id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              S'inscrire / Se connecter
            </a>
            <div class="dropdown-menu " aria-labelledby="navbarDropdown-connexion">
              <%= link_to "Inscrivez-vous", new_user_registration_path , class: "dropdown-item" %>
              <%= link_to "Connexion", new_user_session_path, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Event-THP</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.0/darkly/bootstrap.min.css" integrity="sha384-Bo21yfmmZuXwcN/9vKrA5jPUMhr7znVBBeLxT9MA4r2BchhusfJ6+n8TLGUcRAtL" crossorigin="anonymous">

    <!--  Font Awesome  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash' %>

  
    <div class="content">
      <%= yield %>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <%= render 'layouts/footer' %>
  </body>

</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="view jarallax">
  <div class="mask rgba-indigo-slight">
    <div class="container h-100 d-flex justify-content-center align-items-center">
      <div class="row pt-5 mt-3">
        <div class="col-md-12 mb-3">
          <div class="intro-info-content text-center">
            <h1 class="display-3 blue-text mb-5 wow fadeInDown">
              Bonjour <span class="text-success"> <%= @user.first_name %> </span> !<br> Comment allez vous aujourd'hui ?
            </h1>
            <h5 class="text-uppercase blue-text mb-5 mt-1 font-weight-bold wow fadeInDown">HEUREUX DE VOUS REVOIR PARMI NOUS</h5>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="Userinfos">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" href="#prenom">Prénom</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#nom">Nom</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#description">Description</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#email">Email</a>
    </li>
  </ul>
  <div class="tab-content text-center">
    <div class="tab-pane fade active show" id="prenom">
      <p><%= @user.first_name %></p>
    </div>
    <div class="tab-pane fade " id="nom">
      <p> <%= @user.last_name %></p>
    </div>
    <div class="tab-pane fade " id="description">
      <p> <%= @user.description %></p>
    </div>
    <div class="tab-pane fade " id="email">
      <p> <%= @user.email %></p>
    </div>
  </div>
</div>

<div class="text-center" style="margin: 35px 0;">
  <%= link_to "Ajouter un event", new_event_path , class: "btn btn-outline-danger ", style: "margin-right: 20px" %>
  <%= link_to "Editer votre profil", edit_user_registration_path , class: "btn btn-outline-warning " %>
</div>

<div class ='align-middle text-center'>
  <h6 class="withborder">Voici la liste de vos <strong>events</strong> :</h6>
      <% @events.each do |event| %>
        <div class="card">
          <div class="card-body">
            <h5 class="mt-0 text-center"><%= event.title %></h5>
            <p class="card-text text-info"> <%= event.start_date.strftime("%d %B %Y") %></p>
            <%= link_to "Afficher cet event", event_path(:id => event.id), class: 'btn btn-outline-success btn-sm' %>
          </div>
        </div>
    <% end %>
</div>